version: '3.8'

services:
  apache:
    image: httpd:latest
    container_name: apache-container
    ports:
      - "80:80"
    volumes:
      - ./front:/usr/local/apache2/htdocs

  couchdb:
    image: couchdb:latest
    container_name: couch-container
    ports:
      - "8080:5984"
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    volumes:
      - couchdb_data:/opt/couchdb/data

  nodejs:
    image: node:latest
    container_name: node-container
    working_dir: /app
    volumes:
      - ./back:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && node index.js"

volumes:
  couchdb_data:
